- name: Logstash - Install Java
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: Logstash - Elastic Repo GPG Key
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Logstash - Elastic Repo
  yum_repository:
    name: Logstash-2.4
    description: Logstash repository for 2.4.x packages
    baseurl: https://packages.elastic.co/logstash/2.4/centos
    gpgcheck: yes
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Logstash - Install Logstash
  yum:
    name: logstash
    state: latest
  
