---
- name: ELK_common
  hosts: all
  become: true
  gather_facts: true
  roles:
  - role: common

    #- name: Logstash
    #hosts: logstash
    #become: true
    #roles:
      #- role: logstash

- name: Fluentd Forwarder
  hosts: fluentdfw
  become: true
  roles:
    - role: fluentd-fw


- name: Fluentd Aggregator
  hosts: fluentdag
  become: true
  roles:
    - role: fluentd-ag

      #- name: Redis
      #hosts: redis
      #become: true
      #roles:
        #- role: redis

- name: Elasticsearch
  hosts: elasticsearch
  become: true
  roles:
  - role: elasticsearch

- name: Kibana
  hosts: kibana
  become: true
  roles:
  - role: kibana
