#- name: Kibana - Install Java
#yum:
  #name: java-1.8.0-openjdk
  #state: latest

- name: Kibana - Kibana Repo GPG Key
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Kibana - Kibana Repo
  yum_repository:
    name: kibana-4.5
    description: Kibana repository for 4.5.x packages
    baseurl: https://packages.elastic.co/kibana/4.5/centos
    gpgcheck: yes
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Kibana - Install Kibana
  yum:
    name: kibana
    state: latest

# This will work in Ansible 2.2 until then we will have to use the command module
#- name: Kibana - Enable Kibana
#systemd:
  #daemon_reload: yes
  #name: elasticsearch
  #enabled: yes
  #state: started 

- name: Kibana - Reload SystemD
  command: /bin/systemctl daemon-reload

- name: Kibana - Enable Service
  command: /bin/systemctl enable kibana.service

- name: Kibana - Start Service
  command: /bin/systemctl start kibana.service
