- name: Kibana - Kibana Repo GPG Key
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Kibana - Kibana Repo
  yum_repository:
    name: kibana-5.x
    description: Kibana repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    params: 
      autorefresh=1
      type=rpm-md

- name: Kibana - Install Kibana
  yum:
    name: kibana
    state: latest
  register: kibanainstalled

- name: Kibana Config
  template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
  register: kibanainstalled

# This will work in Ansible 2.2 until then we will have to use the command module
#- name: Kibana - Enable Kibana
#systemd:
  #daemon_reload: yes
  #name: elasticsearch
  #enabled: yes
  #state: started 

- name: Kibana - Start Service
  service:
    name: kibana
    enabled: yes
    state: restarted
  when: kibanainstalled.changed

#- name: Kibana - Enable Service
  #command: /bin/systemctl enable kibana.service
  #when: kibanainstalled.changed

#- name: Kibana - Start Service
  #command: /bin/systemctl start kibana.service
  #when: kibanainstalled.changed
