- name: Elasticsearch - Install Java
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: Elasticsearch - Elastic Repo GPG Key
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Elasticsearch - Elastic Repo
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository for 5.x packages
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    params:
      autorefresh=1
      type=rpm-md

- name: Elasticsearch - Install Elasticsearch
  yum:
    name: elasticsearch
    state: latest
  register: esinstalled

- name: Replace elasticsearch.yml
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    backup: yes
  when: esinstalled.changed

# This will work in Ansible 2.2 until then we will have to use the command module
#- name: Elasticsearch - Enable Elasticsearch
#systemd:
  #daemon_reload: yes
  #name: elasticsearch
  #enabled: yes
  #state: started 

- name: Elasticsearch - Start Service
  service:
    name: elasticsearch
    enabled: yes
    state: restarted
  when: esinstalled.changed



#- name: Elasticsearch - Enable Service
  #command: /bin/systemctl enable elasticsearch.service
  #when: esinstall.changed

#- name: Elasticsearch - Start Service
  #command: /bin/systemctl start elasticsearch.service
  #when: esinstall.changed
